################################################################################
##
## SubSemi
##
## Calculating the closure of a subarray of a multiplication table, i.e.
## a semigroup generated by some elements inside the multiplication table of
## a bigger semigroup.
##
## Copyright (C) 2013-2015  Attila Egri-Nagy
##

DeclareGlobalFunction("ClosureByIncrements");
DeclareGlobalFunction("ClosureByLocalTables");
DeclareGlobalFunction("ClosureByGlobalTables");

DeclareGlobalFunction("SgpInMulTab");
DeclareGlobalFunction("IsInSgp");

DeclareGlobalFunction("IsMaximalSubSgp");

DeclareGlobalFunction("IsClosedSubTable");
DeclareGlobalFunction("MissingElements");
